### PR TITLE
adding overlays from the forum thread that were missing in the repo

### PR DESCRIPTION
**Pull request by jdorion**
Hi UDb23 and meleu, I added the 4 missing overlays from the forum thread to the repository!

### CODE REVIEW

**Review by meleu — CHANGES_REQUESTED** [review]
Thanks. But I noticed that the Space Invaders overlay image file isn't following the convetion we discussed on the forum.

We decided to use `ROMName_ArtistName.png`. And the Space Invaders image file is named `inv_mz_ud.png`. I think it should be `invaders_mz_udb.png` (I'm assuming that mz refers to Metalzoic, the creator of some original image @UDb23 was inspired).

**edit**: remember to change the `invaders.cfg` accordingly!

**Comment by jdorion** [comment]
I literally just downloaded the zips that UDb23 had posted and extracted
them into the repo, I made no changes whatsoever. I'll go make the change
and resubmit tomorrow evening after work!

**Comment by UDb23** [comment]
Yes, please keep mz in the name; as @meleu correctly thought it refers to original creator.
thanks!

**Comment by meleu** [comment]
@UDb23 you can merge it and I'll do the corrections I'm suggesting. And then you merge my corrections. :-)

**Comment by UDb23** [comment]
ok

**Pull request merged**
