### PR TITLE
1600x1200 backdrop for Omega Race

### PR DESCRIPTION
**Pull request by Taranchul**
Don't wonder about the "mkdir" file. I had to make it to create the subdirectory via Githubs web interface which doesn't support creating empty directories.

### CODE REVIEW

**Comment by UDb23** [comment]
to create a new folder with github using web browser access, just create a "dummy" file by entering the new full path for that file (including the new folder in the path I mean); that will create the file inside the new folder (and therefore github creates that folder).

**Comment by Taranchul** [comment]
On 26.01.19 16:49, UDb23 wrote:
> to create a new folder with github using web browser access, just create a "dummy" file by entering the new full path for that file (including the new folder in the path I mean); that will create the file inside the new folder (and therefore github creates that folder).

Yes, that's exactly what I did with the file "mkdir". Or do you mean
another kind of "dummy file"?

Cheers

**Comment by UDb23** [comment]
ok, that's it.
thought mkdir was a line command ....misunderstood :-))

**Comment by Taranchul** [comment]
On 26.01.19 16:57, UDb23 wrote:
> ok, that's it.
> thought mkdir was a line command ....misunderstood :-))

Actually, I named it like the command to tell about its purpose. :D

**Pull request merged**
