### PR TITLE
Made a few tweaks and uploaded simbz23 new overlays

### PR DESCRIPTION
**Pull request by backstander**
New overlays by simbz23: Popeye and Punch-Out!!

### CODE REVIEW

**Comment by meleu** [comment]
I think @simbz33 will maintain his own repo. Maybe it's better send the tweaks to his repo too.

**Comment by simbz33** [comment]
@meleu @backstander Yes, I will be maintaining my own repo, because I do enjoy creating and keeping an archive of any work I do :-)

**Comment by backstander** [comment]
If i can figure it out I'll also merge these changes to simbz33's repo
I was hoping to do this without forking it but I think I'll have to.

**Comment by meleu** [comment]
@simbz33 I'll submit a PR here deleting your files, just to avoid repetition. And then will add your repo to the new script's repo list. ;-)

The @backstander 's repo will ve in the list too.

**Pull request closed without merging**
