### PR TITLE
using relative paths in info.txt

### PR DESCRIPTION
**Pull request by meleu**
There's no need to duplicate files. Just use a relative path. ;-)

### CODE REVIEW

**Comment by UDb23** [comment]
well done.

**Comment by meleu** [comment]
Since you merged the info.txt, you can delete the duplicated files:
- https://github.com/UDb23/rpie-ovl/blob/master/arcade/The%20End/fba/theend_udb-ovl.png
- https://github.com/UDb23/rpie-ovl/blob/master/arcade/The%20End/fba/theend.cfg

**Comment by UDb23** [comment]
Done, thanks.

**Comment by UDb23** [comment]
Gyruss folder and info.txt modified to be compliant with latest script features.

**Pull request merged**
